# This workflow will auto-version when pull-requests are merged to main.
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Release

on:
  pull_request:
    branches: 
      - "main"
    types:
      - closed

permissions:
  contents: write

jobs:
  release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: Git checkout
      uses: actions/checkout@v4
      with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}

    # please note, this will likely fail if the auto versioning workflow was not first run on the branch before merging.
    # if this happens you may need to delete the tag on GitHub that does not correspond to a release.
    - name: Conventional Changelog Action
      id: changelog
      uses: TriPSs/conventional-changelog-action@v5.2.1
      with:
        github-token: ${{ secrets.github_token }}
        version-file: "VERSION.json"
        release-count: '30'
        git-branch: ${{ github.event.pull_request.head.ref }}

    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.changelog.outputs.tag }}
        release_name: ${{ steps.changelog.outputs.tag }}
        body: ${{ steps.changelog.outputs.clean_changelog }}
