# This workflow will perform basic automatic testing on pyscan classes
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Basic Auto Tests

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        
    - name: Install package
      run: |
        python -m pip install --upgrade pip
        python -m pip install wheel
        python -m pip install flake8
        python -m pip install pytest
        python -m pip install nbmake
        python -m pip install -e .

    - name: Test with pytest
      run: |
        pytest
